### PR TITLE
install example sensor_map, minor reworking of install.py

### PR DESCRIPTION
**Pull request by vinceskahan**
This installs the example Tempest sensor_map since so many users seem to not do that step.

I also did a little refactoring of install.py to line up with some previous work I did along similar 'seed weewx.conf better' lines with the Belchertown skin, but it should be hopefully obvious.  Also added a comment reminding the user the example is an EXAMPLE and some editing is still required.

### CODE REVIEW

**Comment by vinceskahan** [comment]
Added @property to driver so v5.0.2 and earlier v5.0.x weewx station registrations work again.  This seems to be an undocumented breaking change under the hood as weewx.  The actual driver itself works fine, but the station registration magic seems to require this addition to keep working.

**Comment by captain-coredump** [comment]
Thank you!

**Comment by captain-coredump** [comment]
Added.  Thank you!

**Comment by captain-coredump** [comment]
Added.  Thank you!

**Comment by captain-coredump** [comment]
Added.  Thank you!

**Comment by captain-coredump** [comment]
Added.  Thank you!

**Comment by captain-coredump** [comment]
Added.  Thank you!

**Pull request merged**
